version: '3'
services:
  db:
    image: postgres:10.3
    platform: linux/amd64
    expose:
      - "5432"
  redis:
    image: redis
    platform: linux/amd64
    expose:
      - "6379"
  worker:
    platform: linux/amd64
    container_name: mridata_worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: ['bash', 'start_worker.sh']
    links:
      - db
      - redis
    depends_on:
      - redis
    environment:
      - DEBUG=1
      - MEDIA_ROOT=/media
      - TEMP_ROOT=/temp
    volumes:
      - ./src:/src
      - ./media:/media
      - ./temp:/temp
  web:
    container_name: mridata_web
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ['bash', 'start_web.sh']
    ports:
      - "8000:8000"
    links:
      - db
      - redis
      - worker
    depends_on:
      - db
    environment:
      - DEBUG=1
      - MEDIA_ROOT=/media
      - TEMP_ROOT=/temp
    volumes:
      - ./src:/src
      - ./media:/media
      - ./temp:/temp
