FROM python:3.9-slim-buster

MAINTAINER Frank Ong <frankong@berkeley.edu>

# Python
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY start_web.sh start_web.sh
EXPOSE 8000
