# Generated by Django 2.0.3 on 2018-03-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='flip_angle',
            field=models.FloatField(default=-1, verbose_name='Flip Angle [degree]'),
        ),
        migrations.AlterField(
            model_name='data',
            name='resolution_x',
            field=models.FloatField(default=-1, verbose_name='Resolution x [mm]'),
        ),
        migrations.AlterField(
            model_name='data',
            name='resolution_y',
            field=models.FloatField(default=-1, verbose_name='Resolution y [mm]'),
        ),
        migrations.AlterField(
            model_name='data',
            name='resolution_z',
            field=models.FloatField(default=-1, verbose_name='Resolution z [mm]'),
        ),
        migrations.AlterField(
            model_name='data',
            name='scanner_field',
            field=models.FloatField(default=-1, verbose_name='Field Strength [T]'),
        ),
        migrations.AlterField(
            model_name='data',
            name='scanner_model',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='te',
            field=models.FloatField(default=-1, verbose_name='Echo Time [ms]'),
        ),
        migrations.AlterField(
            model_name='data',
            name='ti',
            field=models.FloatField(default=-1, verbose_name='Inversion Time [ms]'),
        ),
        migrations.AlterField(
            model_name='data',
            name='tr',
            field=models.FloatField(default=-1, verbose_name='Repetition Time [ms]'),
        ),
    ]
