# Generated by Django 2.0.3 on 2018-03-24 02:15

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mridata.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('anatomy', models.CharField(default='N/A', max_length=100)),
                ('sequence_name', models.CharField(default='N/A', max_length=100)),
                ('trajectory', models.CharField(default='N/A', max_length=100)),
                ('fullysampled', models.NullBooleanField()),
                ('scanner_vendor', models.CharField(default='N/A', max_length=100)),
                ('scanner_model', models.CharField(default='N/A', max_length=100)),
                ('scanner_field', models.FloatField(default=-1, verbose_name='Field Strength [T]')),
                ('matrix_size_x', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('matrix_size_y', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('matrix_size_z', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_channels', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_slices', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_repetitions', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_contrasts', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('resolution_x', models.FloatField(default=-1, verbose_name='Resolution x [mm]')),
                ('resolution_y', models.FloatField(default=-1, verbose_name='Resolution y [mm]')),
                ('resolution_z', models.FloatField(default=-1, verbose_name='Resolution z [mm]')),
                ('flip_angle', models.FloatField(default=-1, verbose_name='Flip Angle [degree]')),
                ('te', models.FloatField(default=-1, verbose_name='Echo Time [ms]')),
                ('tr', models.FloatField(default=-1, verbose_name='Repetition Time [ms]')),
                ('ti', models.FloatField(default=-1, verbose_name='Inversion Time [ms]')),
                ('ismrmrd_file', models.FileField(upload_to=mridata.models.save_ismrmrd_file, verbose_name='ISMRMRD File')),
                ('thumbnail_file', models.ImageField(upload_to='')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('anatomy', models.CharField(max_length=100)),
                ('fullysampled', models.NullBooleanField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('failed', models.NullBooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeData',
            fields=[
                ('tempdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mridata.TempData')),
                ('ge_pfile', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='"/temp"'), upload_to=mridata.models.save_ge_pfile)),
            ],
            bases=('mridata.tempdata',),
        ),
        migrations.CreateModel(
            name='IsmrmrdData',
            fields=[
                ('tempdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mridata.TempData')),
                ('ismrmrd_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='"/temp"'), upload_to=mridata.models.save_ismrmrd_file)),
            ],
            bases=('mridata.tempdata',),
        ),
        migrations.CreateModel(
            name='PhilipsData',
            fields=[
                ('tempdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mridata.TempData')),
                ('philips_raw_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='"/temp"'), upload_to=mridata.models.save_philips_raw_file)),
                ('philips_sin_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='"/temp"'), upload_to=mridata.models.save_philips_sin_file)),
                ('philips_lab_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='"/temp"'), upload_to=mridata.models.save_philips_lab_file)),
            ],
            bases=('mridata.tempdata',),
        ),
        migrations.CreateModel(
            name='SiemensData',
            fields=[
                ('tempdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mridata.TempData')),
                ('siemens_dat_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='"/temp"'), upload_to=mridata.models.save_siemens_dat_file)),
            ],
            bases=('mridata.tempdata',),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
