# Generated by Django 2.0.3 on 2018-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='scanner_model',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='scanner_vendor',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='sequence_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='trajectory',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='anatomy',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
