# Generated by Django 2.0.3 on 2018-03-24 02:18

import django.core.files.storage
from django.db import migrations, models
import mridata.models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gedata',
            name='ge_pfile',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='/src/temp'), upload_to=mridata.models.save_ge_pfile),
        ),
        migrations.AlterField(
            model_name='ismrmrddata',
            name='ismrmrd_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='/src/temp'), upload_to=mridata.models.save_ismrmrd_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_lab_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='/src/temp'), upload_to=mridata.models.save_philips_lab_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_raw_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='/src/temp'), upload_to=mridata.models.save_philips_raw_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_sin_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='/src/temp'), upload_to=mridata.models.save_philips_sin_file),
        ),
        migrations.AlterField(
            model_name='siemensdata',
            name='siemens_dat_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/temp/', location='/src/temp'), upload_to=mridata.models.save_siemens_dat_file),
        ),
    ]
