# Generated by Django 2.0.3 on 2018-03-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0002_auto_20180323_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='matrix_size_x',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='data',
            name='matrix_size_y',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='data',
            name='matrix_size_z',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='data',
            name='number_of_channels',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='data',
            name='number_of_contrasts',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='data',
            name='number_of_repetitions',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='data',
            name='number_of_slices',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='anatomy',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
