# Generated by Django 2.0.3 on 2018-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0002_auto_20180326_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdata',
            name='anatomy',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
