# Generated by Django 2.0.3 on 2018-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0003_auto_20180323_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
