# Generated by Django 2.0.3 on 2018-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0003_auto_20180326_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='horizontal_flip_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='transpose_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='vertical_flip_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='horizontal_flip_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='transpose_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='vertical_flip_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
