# Generated by Django 2.0.3 on 2018-03-28 07:30

from django.db import migrations, models
import mridata.models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0003_auto_20180327_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gedata',
            name='ge_file',
            field=models.FileField(upload_to=mridata.models.save_ge_file),
        ),
        migrations.AlterField(
            model_name='ismrmrddata',
            name='ismrmrd_file',
            field=models.FileField(upload_to=mridata.models.save_ismrmrd_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_lab_file',
            field=models.FileField(upload_to=mridata.models.save_philips_lab_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_raw_file',
            field=models.FileField(upload_to=mridata.models.save_philips_raw_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_sin_file',
            field=models.FileField(upload_to=mridata.models.save_philips_sin_file),
        ),
        migrations.AlterField(
            model_name='siemensdata',
            name='siemens_dat_file',
            field=models.FileField(upload_to=mridata.models.save_siemens_dat_file),
        ),
    ]
