# Generated by Django 2.0.4 on 2018-04-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0004_auto_20180328_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='thumbnail_horizontal_flip',
        ),
        migrations.RemoveField(
            model_name='data',
            name='thumbnail_rotate_90_degree',
        ),
        migrations.RemoveField(
            model_name='data',
            name='thumbnail_vertical_flip',
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='thumbnail_rotate_90_degree',
        ),
        migrations.AddField(
            model_name='tempdata',
            name='thumbnail_no_ifft_along_readout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='thumbnail_transpose',
            field=models.BooleanField(default=False),
        ),
    ]
