# Generated by Django 2.0.3 on 2018-03-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0004_data_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='downloads',
        ),
    ]
