# Generated by Django 2.0.3 on 2018-03-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0005_remove_data_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='additional_comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='data',
            name='paper_references',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='additional_comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='paper_references',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='anatomy',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='scanner_model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='scanner_vendor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='sequence_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='trajectory',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='anatomy',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
