# Generated by Django 2.0.3 on 2018-03-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0005_auto_20180327_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='horizontal_flip_thumbnail',
        ),
        migrations.RemoveField(
            model_name='data',
            name='rotate_90_thumbnail',
        ),
        migrations.RemoveField(
            model_name='data',
            name='vertical_flip_thumbnail',
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='horizontal_flip_thumbnail',
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='rotate_90_thumbnail',
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='vertical_flip_thumbnail',
        ),
        migrations.AddField(
            model_name='data',
            name='thumbnail_horizontal_flip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='thumbnail_rotate_90_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='thumbnail_vertical_flip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='thumbnail_horizontal_flip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='thumbnail_rotate_90_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='thumbnail_vertical_flip',
            field=models.BooleanField(default=False),
        ),
    ]
