# Generated by Django 2.0.4 on 2018-04-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0005_auto_20180407_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdata',
            name='thumbnail_no_ifft_along_readout',
        ),
        migrations.AddField(
            model_name='tempdata',
            name='thumbnail_fftshift_along_z',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='thumbnail_no_ifft_along_x',
            field=models.BooleanField(default=False),
        ),
    ]
