# Generated by Django 2.0.3 on 2018-03-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0006_auto_20180324_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='additional_comments',
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='additional_comments',
        ),
        migrations.AddField(
            model_name='data',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='paper_references',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='paper_references',
            field=models.TextField(blank=True, default=''),
        ),
    ]
