# Generated by Django 2.0.3 on 2018-03-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0007_auto_20180324_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='paper_references',
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='paper_references',
        ),
        migrations.AddField(
            model_name='data',
            name='references',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='references',
            field=models.TextField(blank=True, default=''),
        ),
    ]
