# Generated by Django 2.0.4 on 2018-04-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0007_remove_tempdata_thumbnail_no_ifft_along_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='project_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='project_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
