# Generated by Django 2.0.4 on 2018-04-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0008_auto_20180408_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='project_name',
        ),
        migrations.AddField(
            model_name='data',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mridata.Project'),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mridata.Project'),
        ),
    ]
