# Generated by Django 2.0.4 on 2018-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0009_auto_20180410_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
