# Generated by Django 2.0.3 on 2018-06-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0010_auto_20180410_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='funding_support',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='funding_support',
            field=models.TextField(blank=True, default=''),
        ),
    ]
