# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-01 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0012_auto_20180731_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdata',
            name='thumbnail_fftshift_along_z',
        ),
    ]
