# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0015_auto_20180731_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeAwsData',
            fields=[
                ('tempdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mridata.TempData')),
                ('ge_aws_file', s3direct.fields.S3DirectField()),
            ],
            bases=('mridata.tempdata',),
        ),
        migrations.CreateModel(
            name='IsmrmrdAwsData',
            fields=[
                ('tempdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mridata.TempData')),
                ('ismrmrd_file', s3direct.fields.S3DirectField()),
            ],
            bases=('mridata.tempdata',),
        ),
        migrations.CreateModel(
            name='PhilipsAwsData',
            fields=[
                ('tempdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mridata.TempData')),
                ('philips_raw_file', s3direct.fields.S3DirectField()),
                ('philips_sin_file', s3direct.fields.S3DirectField()),
                ('philips_lab_file', s3direct.fields.S3DirectField()),
            ],
            bases=('mridata.tempdata',),
        ),
        migrations.CreateModel(
            name='SiemensAwsData',
            fields=[
                ('tempdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mridata.TempData')),
                ('siemens_dat_file', s3direct.fields.S3DirectField()),
            ],
            bases=('mridata.tempdata',),
        ),
    ]
