# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-04 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0016_geawsdata_ismrmrdawsdata_philipsawsdata_siemensawsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ismrmrd_file',
            field=models.FileField(upload_to='uploads/', verbose_name='ISMRMRD File'),
        ),
        migrations.AlterField(
            model_name='gedata',
            name='ge_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ismrmrddata',
            name='ismrmrd_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_lab_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_raw_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_sin_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='siemensdata',
            name='siemens_dat_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
