# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-04 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0017_auto_20180803_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ismrmrd_file',
            field=models.FileField(upload_to='', verbose_name='ISMRMRD File'),
        ),
    ]
