# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-04 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import mridata.models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0019_auto_20180803_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gedata',
            name='ge_file',
            field=models.FileField(upload_to=mridata.models.save_ge_file),
        ),
        migrations.AlterField(
            model_name='ismrmrddata',
            name='ismrmrd_file',
            field=models.FileField(blank=True, upload_to=mridata.models.save_ismrmrd_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_lab_file',
            field=models.FileField(upload_to=mridata.models.save_philips_lab_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_raw_file',
            field=models.FileField(upload_to=mridata.models.save_philips_raw_file),
        ),
        migrations.AlterField(
            model_name='philipsdata',
            name='philips_sin_file',
            field=models.FileField(upload_to=mridata.models.save_philips_sin_file),
        ),
        migrations.AlterField(
            model_name='siemensdata',
            name='siemens_dat_file',
            field=models.FileField(upload_to=mridata.models.save_siemens_dat_file),
        ),
    ]
