# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0020_auto_20180804_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='thumbnail_horizontal_flip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='thumbnail_transpose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='thumbnail_vertical_flip',
            field=models.BooleanField(default=False),
        ),
    ]
