# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0022_data_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tags_model',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
