# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0023_data_tags_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='tags_model',
        ),
    ]
