# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0024_remove_data_tags_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='data',
            name='tags',
        ),
        migrations.AddField(
            model_name='data',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
