# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mridata', '0026_data_tags_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='tags',
        ),
    ]
