# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('mridata', '0028_auto_20181114_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tempdata',
            name='tags',
        ),
        migrations.AlterField(
            model_name='data',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='mridata.TaggedData', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='taggeddata',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mridata.Data'),
        ),
        migrations.AddField(
            model_name='taggeddata',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mridata_taggeddata_items', to='taggit.Tag'),
        ),
    ]
